/*
 * This source file was generated by the Gradle 'init' task
 */
package com.apakhomov.game;

import java.net.ServerSocket;
import java.net.Socket;
import java.util.List;

public class Server {

    public Server() {
    }

    public void start() {
        System.out.println("Server started");
        try {
            ServerSocket socket = new ServerSocket(8080);
            System.out.println("Connected to server");

            Socket socket1 = socket.accept();
            Player p1 = new NetworkPlayer(socket1);
            System.out.println("Connected to client: " + p1.username());

            Socket socket2 = socket.accept();
            Player p2 = new NetworkPlayer(socket2);
            System.out.println("Connected to client: " + p2.username());

            Player winner = new Game(List.of(p1, p2)).start();
            System.out.println("Game over, winner is: " + winner.username());

            socket.close();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }



    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        new Server().start();
    }
}
