/*
 * This source file was generated by the Gradle 'init' task
 */
package com.apakhomov.game.server;

import com.apakhomov.game.GameController;
import com.apakhomov.game.events.EventBus;
import com.apakhomov.game.exec.VirtualThreadsWorker;

import java.net.ServerSocket;

public class Server {
    private final ServerConfiguration configuration;

    public Server(ServerConfiguration configuration) {
        this.configuration = configuration;
    }

    public void start() {
        try (var socket = new ServerSocket(configuration.port());
             var worker = new VirtualThreadsWorker()) {
            System.out.println("Server started");

            var bus = new EventBus(worker);
            // todo
            var controller = new GameController(bus, worker);

            try (var manager = new ConnectionsManager(new PlayersPool(bus, worker), bus)) {
                while (true) {
                    manager.handle(socket.accept());
                }
            }

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }


    public static void main(String[] args) {
        new Server(new ServerConfiguration()).start();
    }
}
